/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import logic.HexBoard;
import logic.HexButton;

/**
 *
 * @author Jenner Rodriguez
 */
public class Matriz extends javax.swing.JDialog {
    
    private int size;
    private HexBoard board;
    /**
     * Creates new form Matriz
     */
    public Matriz(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jPnl_board.setBackground(Color.white);
        this.bt_Jugar.setVisible(false);
        this.bt_CambiarTam.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl_board = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_Tamaño = new javax.swing.JLabel();
        ComboBoxNum = new javax.swing.JComboBox<>();
        bt_Jugar = new javax.swing.JButton();
        bt_Generar = new javax.swing.JButton();
        bt_CambiarTam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPnl_boardLayout = new javax.swing.GroupLayout(jPnl_board);
        jPnl_board.setLayout(jPnl_boardLayout);
        jPnl_boardLayout.setHorizontalGroup(
            jPnl_boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_boardLayout.createSequentialGroup()
                .addContainerGap(628, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(69, 69, 69))
        );
        jPnl_boardLayout.setVerticalGroup(
            jPnl_boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_boardLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addGap(0, 528, Short.MAX_VALUE))
        );

        lb_Tamaño.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        lb_Tamaño.setText("Seleccionar Tamaño");

        ComboBoxNum.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        ComboBoxNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12" }));
        ComboBoxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNumActionPerformed(evt);
            }
        });

        bt_Jugar.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        bt_Jugar.setText("Jugar");
        bt_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_JugarActionPerformed(evt);
            }
        });

        bt_Generar.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        bt_Generar.setText("Generar");
        bt_Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GenerarActionPerformed(evt);
            }
        });

        bt_CambiarTam.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        bt_CambiarTam.setText("Cambiar Tamaño");
        bt_CambiarTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CambiarTamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPnl_board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ComboBoxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Generar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_CambiarTam)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnl_board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_Generar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_CambiarTam, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxNumActionPerformed

    private void bt_GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GenerarActionPerformed
        // TODO add your handling code here:
        this.size = (int) Integer.parseInt((String) ComboBoxNum.getSelectedItem());        
        setMatriz(size);
        this.bt_Generar.setVisible(false);
        this.lb_Tamaño.setVisible(false);
        this.ComboBoxNum.setVisible(false);
        this.bt_Jugar.setVisible(true);
        this.bt_CambiarTam.setVisible(true);
    }//GEN-LAST:event_bt_GenerarActionPerformed

    private void bt_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_JugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_JugarActionPerformed

    private void bt_CambiarTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CambiarTamActionPerformed
        // TODO add your handling code here:
        this.jPnl_board.removeAll(); //Aquí estoy borrando la matriz que había, pero si la vuelvo a generar lo hace mal
        this.lb_Tamaño.setVisible(true);
        this.ComboBoxNum.setVisible(true);
        this.bt_Generar.setVisible(true);
        this.bt_Jugar.setVisible(false);
        this.bt_CambiarTam.setVisible(false);
    }//GEN-LAST:event_bt_CambiarTamActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Matriz dialog = new Matriz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void setMatriz(int size) {
        board = new HexBoard(size);
        HexButton button = null;
        int x = 40;
        int y = 0;
        
        for (int i = 0; i < size + 2; i++) {
            for (int j = 0; j < size + 2; j++) {
                button = new HexButton();
                button.setA(i);
                button.setB(j);
                if (i == 0 || i == (size + 1)) {
                    button.setBackground(Color.red);
                    button.setBounds(x, y, 40, 40);
                    button.setEnabled(false);
                    this.jPnl_board.add(button);
                } else if (j == 0 || j == (size + 1)) {
                    button.setBackground(Color.blue);
                    button.setBounds(x, y, 40, 40);
                    button.setEnabled(false);
                    this.jPnl_board.add(button);
                } else {
                    button.setBounds(x, y, 40, 40);
                    this.jPnl_board.add(button);
                }
                x += 32;
            }
            x = 56 + (i * 15);
            y += 29;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxNum;
    private javax.swing.JButton bt_CambiarTam;
    private javax.swing.JButton bt_Generar;
    private javax.swing.JButton bt_Jugar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPnl_board;
    private javax.swing.JLabel lb_Tamaño;
    // End of variables declaration//GEN-END:variables
}
